server:
  port: 8889
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhou_jiale/spring-cloud.git
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka